[functions]
  directory = "netlify"
  included_files = ["expressions/**/*.png", "expressions-resized/**/*.png"]
  node_bundler = 'esbuild'


[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
