[functions]
  directory = "netlify"
  included_files = ["expressions-resized/**", "expressions-resized/400x400/**", "expressions-resized/400x400/background/**"]
  node_bundler = "esbuild"
  external_node_modules = ["expressions-resized"]

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
